spring:
  application:
    name: ship-service
  datasource:
    url: jdbc:postgresql://localhost:5432/star-cruises-microservices
    username: postgres
    password: newton123
    driver-class-name: org.postgresql.Driver
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    status-page-url-path: http://localhost:8010/eureka/info
    health-check-url-path: http://localhost:8010/eureka/health
    secure-port-enabled: true
    non-secure-port-enabled: false