spring:
  application:
    name: user-service
server:
  port: 8091
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    status-page-url-path: http://localhost:8010/eureka/info
    health-check-url-path: http://localhost:8010/eureka/health
    secure-port-enabled: true
    non-secure-port-enabled: false